plugins {
    id 'org.jetbrains.intellij.platform' version '2.10.5'
    id "org.ajoberstar.grgit" version "5.0.0-rc.3"
    id "java"
    id "idea"
}

group = 'net.ishchenko.idea.nginx'
version = '0.1.16'

repositories {
    mavenLocal()
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

ext {
    since = "253.28294.0"
    until = "261.*"
}

dependencies {
    intellijPlatform {
        intellijIdea '2025.3'
        bundledPlugin 'com.intellij.java'
    }
    implementation 'com.jgoodies:jgoodies-common:1.8.1'
    implementation 'com.jgoodies:jgoodies-forms:1.9.0'
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
}

sourceSets {
    main {
        java.srcDirs = ['src', 'gen']
        resources.srcDirs = ['resources']
    }
    test {
        java.srcDirs = ['tests']
    }
}

intellijPlatform {
    pluginConfiguration {
        id = 'net.ishchenko.idea.nginx'
        name = 'nginx-support'
        version = project.version

        ideaVersion {
            sinceBuild = since
            untilBuild = until
        }
    }

    pluginVerification {
        ides {
            ide("IU", since, false)
        }
    }
}

tasks.register('generateDocumentation', JavaExec) {
    mainClass = 'net.ishchenko.idea.nginx.KeywordsFromSourcesGenerator'
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register('getRepos') {
    doLast {
        def path = 'vendor/nginx'
        if (!file(path).exists()) {
            Grgit.clone(dir: file(path), uri: 'https://github.com/nginx/nginx.git')
        } else {
            Grgit.open(dir: file(path)).pull()
        }
        def luaPath = 'vendor/lua-nginx-module'
        if (!file(luaPath).exists()) {
            Grgit.clone(dir: file(luaPath), uri: 'https://github.com/openresty/lua-nginx-module.git')
        } else {
            Grgit.open(dir: file(luaPath)).pull()
        }
    }
}
